{
  Errors errors=proccedValidation("{val,obj -> return ['test.message', 'arg', 123L]}");
  assertTrue(errors.hasErrors());
  FieldError error=errors.getFieldError(PROP_NAME);
  System.out.println(error);
  assertTrue(checkErrorCode(error,"testClass.firstName.test.message"));
  Object[] arguments=error.getArguments();
  assertEquals(5,arguments.length);
  assertTrue(arguments[0] instanceof String);
  assertEquals(PROP_NAME,arguments[0]);
  assertTrue(arguments[1] instanceof Class);
  assertEquals(TestClass.class,arguments[1]);
  assertTrue(arguments[2] instanceof String);
  assertEquals("John",arguments[2]);
  assertTrue(arguments[3] instanceof String);
  assertEquals("arg",arguments[3]);
  assertTrue(arguments[4] instanceof Long);
  assertEquals(new Long(123),arguments[4]);
  try {
    proccedValidation("{val, obj -> return [123L,'arg1','arg2']}");
    fail("Validator constraint must throw an exception about wrong closure return");
  }
 catch (  IllegalArgumentException iae) {
  }
}
